services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vrdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: