server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: vehicle-registration
  datasource:
    url: jdbc:postgresql://localhost:5432/vrdb
    username: user
    password: password
    hikari:
      auto-commit: false
      connection-init-sql: SELECT 1;
      connection-test-query: SELECT 1;
      maximum-pool-size: 1
      connection-timeout: 30000
      idleTimeout: 30000
      minimumIdle: ${IDLE_CONNECTION:1}
      isolate-internal-queries: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: false
